POST http://localhost:3333/register/client
Content-Type: application/json
Accept: application/json

{
    "name": "Zé da padaria",
    "email": "kkkkk@gmail.com",
    "password": "kkkkkkkkk"
}

###
POST http://localhost:3333/register/client
Content-Type: application/json
Accept: application/json

{   
    "name": "Admin1234", 
    "email": "admin@gmail.com", 
    "password": "123456789" 
}

###

POST http://localhost:3333/login/client
Content-Type: application/json
Accept: application/json

{
    "name": "Zé da padaria",
    "email": "kkkkk@gmail.com",
    "password": "kkkkkkkkk"
}

###
POST http://localhost:3333/login/client
Content-Type: application/json
Accept: application/json

{
    "name": "Zé da padari",
    "email": "kkkkk@gmail.com",
    "password": "kkkkkkkkk"
}

###
GET http://localhost:3333/get/client/ad0433aa-76d5-453b-bd74-3e5a6e93b353

###
GET http://localhost:3333/get/client/ad80bd8b-c7b3-482c-a4cc-401e39ebd02e

###

GET http://localhost:3333/get/client/list

###

DELETE http://localhost:3333/delete/client/list