POST http://localhost:3333/register/business
Content-Type: application/json
Accept: application/json

{
    "name": "Zé",
    "email": "kkkk@gmail.com",
    "password": "kkkkkkkkk",
    "CNPJ": "12.345.678/0001-95"
}

###
POST http://localhost:3333/register/business
Content-Type: application/json
Accept: application/json

{   
    "name": "Admin123", 
    "email": "adm@gmail.com", 
    "password": "123456789",
    "CNPJ": "98.765.432/0001-60"
}

###

POST http://localhost:3333/login/business
Content-Type: application/json
Accept: application/json

{   
    "name": "Admin123", 
    "email": "adm@gmail.com", 
    "password": "123456789",
    "CNPJ": "98.765.432/0001-60"
}

###
POST http://localhost:3333/login/business
Content-Type: application/json
Accept: application/json

{
    "name": "Zé",
    "email": "kkkk@gmail.com",
    "password": "kkkkkkkkk",
    "CNPJ": "12.345.678/0001-95"
}

###
GET http://localhost:3333/get/business/f345e7eb-3b68-46f5-b00b-a335a990b18d

###
GET http://localhost:3333/get/business/fc1aa167-df6b-4704-9814-036fea10449f

###

GET http://localhost:3333/get/business/list

###

DELETE http://localhost:3333/delete/business/list