POST http://localhost:3333/register/business
Content-Type: application/json
Accept: application/json

{
    "name": "businessMauro",
    "email": "MauroBusiness@gmail.com",
    "password": "Mauro1234",
    "CNPJ": "12.345.678/0001-95"
}

###
POST http://localhost:3333/login/business
Content-Type: application/json
Accept: application/json

{
    "name": "businessMauro",
    "email": "MauroBusiness@gmail.com",
    "password": "Mauro1234",
    "CNPJ": "12.345.678/0001-95"
}

###
POST http://localhost:3333/edit/business
Content-Type: application/json
Accept: application/json

{
    "id": "1b6081f9-d75e-4ef9-826b-0dc9d4d6d6aa",
    "oldName": "businessMauro",
    "newName": "Novo Zé da padaria",
    "oldEmail": "MauroBusiness@gmail.com",
    "newEmail": "SEUZÉDOIS@gmail.com",
    "oldPassword": "Mauro1234",
    "newPassword": "kkkkkkkkkOIMAN"
}

###
GET http://localhost:3333/get/business/f345e7eb-3b68-46f5-b00b-a335a990b18d

###
GET http://localhost:3333/get/business/fc1aa167-df6b-4704-9814-036fea10449f

###

GET http://localhost:3333/get/business/list

###

DELETE http://localhost:3333/delete/business/list